### PR TITLE
#112 Add all missing required params to exception

### LINKED ISSUE #122: Refactor: Improve exception message for required query params
Currently, the error only reports one missing query parameter at a time. Ideally, it should list all missing required parameters.

* 'symbol' is a required query param ...
* 'symbol' and 'date' are required query params ...
* 'symbol', 'date' and 'limit' are required query params ...

### PR DESCRIPTION
**Pull request by andyyngo**
Refactor error  report to show all  missing query parameters in one Exception
Close #122

### CODE REVIEW

**Review by sorndotdev — CHANGES_REQUESTED** [review]

**Comment by andyyngo** [comment]
@sorndotdev could you review this PR?

File: src/test/java/dev/sorn/fmp4j/services/FmpServiceTest.java [hunk 1]
```diff
@@ -34,15 +36,20 @@ class FmpServiceTest {
...
         openMocks(this);
         when(mockConfig.fmpApiKey()).thenReturn(new FmpApiKey("abcdefghij1234567890abcdefghij12"));
         service = new ConcreteFmpService(mockConfig, mockHttpClient);
+
+        multiRequiredService = new MultiRequiredFmpService(mockConfig, mockHttpClient);
     }
 
     @Test
-    void accepts_list_with_correct_type() {
+    @DisplayName("Should accept List with correct element type")
```
Comment (sorndotdev) [inline src/test/java/dev/sorn/fmp4j/services/FmpServiceTest.java]: Please remove DisplayName

File: src/test/java/dev/sorn/fmp4j/services/FmpServiceTest.java [hunk 2]
```diff
@@ -130,15 +135,37 @@ void handles_null_key() {
...
+                        + msg);
+    }
+
+    @Test
+    void should_not_throw_missing_required_params() {
+        // given
+        multiRequiredService.param("page", FmpPage.page(10));
+        multiRequiredService.param("limit", FmpLimit.limit(10));
+
+        // when //then
```
Comment (sorndotdev) [inline src/test/java/dev/sorn/fmp4j/services/FmpServiceTest.java]: Please put spaces between `//` and `then` in all places...

**Comment by sorndotdev** [comment]
@andyyngo that sounds good - I agree
